# Generated by Django 4.1.6 on 2023-02-10 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_testmonial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testmonial',
            new_name='Testimonial',
        ),
    ]
